apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: backend
type: Opaque
data:
  DB_HOST: "bXl0ZXN0ZGIuY2F6bW95a2NrMWNyLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ=="
  DB_USER: "YWRtaW4="
  DB_PASSWORD: "TXlQYXNzMTIzISE="
  DB_NAME: "TXlUZXN0REI="
  DB_PORT: "MzMwNg=="
